### ISSUE TITLE
Port additional voting mechanisms from snapshot.org

### ISSUE THREAD

**Issue by givp** [harmony-one/snapshot#13]
Our modified Snapshot instance currently only supports Single Choice Voting. However, on snapshot.org, when creating a new proposal, you have the option to select several different voting types:

![Screen Recording 2021-09-20 at 03 02 11 PM](https://user-images.githubusercontent.com/205550/134081941-cc7491e2-06c2-462b-bc0c-21f36196e8a2.gif)

## Single Choice Voting
Each voter may select only one choice.

## Approval Voting
Each voter may select any number of choices.

## Quadratic Voting
Each voter may spread voting power across any number of choices. Results are calculated quadratically.

## Ranked Choice Voting
Each voter may select and rank any number of choices. Results are calculated by instant-runoff counting method.

## Weighted voting
Each voter may spread voting power across any number of choices.

This repo is heavily modified and now outdated so the task will not be straight forward. Unfortunately it will require manual customization to integrate.

Voting components: https://github.com/snapshot-labs/snapshot/tree/develop/src/components/Voting
Snapshot docs: https://docs.snapshot.org/

**Comment by victaphu** [comment]
This has been completed and ready for testing
https://harmony-snapshot.netlify.app/

I've also created a PR that can be merged once ready
https://github.com/harmony-one/snapshot/pull/17

Some tests to perform:
- Look at the Test space, there is tests for all the different voting types
- Tested voting on existing spaces (Incubator DAO, JarJar)

Pending tests:
- Restricted multi-select for DAO related spaces (dao-mainnet, dao-testnet, etc)
