### ISSUE TITLE
Creating a snapshot with only staked ones using Vote By Count fails

### ISSUE THREAD

**Issue by victaphu** [harmony-one/snapshot#19]
**Describe the bug**
When creating a vote-by-count option for snapshot and having only staked ones, the system will be unable to load the snapshot for voting. An example of a failed voting page is:
https://gov.harmony.one/#/harmony-creative-dao/proposal/QmZ6xiTHv7RYkCnbThNAi4Knxm2kMiXUgdRQXYU4v9UY1P

**To Reproduce**
1. go to https://gov.harmony.one
2. create a proposal with a wallet with only staked one
3. submit proposal, navigate to new vote
4. example of failure to load: https://gov.harmony.one/#/harmony-creative-dao/proposal/QmZ6xiTHv7RYkCnbThNAi4Knxm2kMiXUgdRQXYU4v9UY1P

**Expected behavior**
Vote is enabled and users can begin voting on the snapshot

**Screenshots**
https://gov.harmony.one/#/harmony-creative-dao/proposal/QmZ6xiTHv7RYkCnbThNAi4Knxm2kMiXUgdRQXYU4v9UY1P

**Desktop (please complete the following information):**
 - OS: MacOSX
 - Browser Chrome/Safari/Brave
 - Version Latest version (V1.32.106)

**Smartphone (please complete the following information):**
n/a

**Additional context**
https://gov.harmony.one/#/harmony-creative-dao/proposal/QmZ6xiTHv7RYkCnbThNAi4Knxm2kMiXUgdRQXYU4v9UY1P

**Comment by Stakeridoo** [comment]
@victaphu What is this new option "added option for using vote by count vs vote by staked tokens"?
https://github.com/harmony-one/snapshot/issues/13#issuecomment-949793843

If you need to run some tests let me know I have Chrome Extension and MetaMask, staked ONE and available ONE and also Ledger (which is actually not working)

When I crashed the Voting I used this options and have voted by a Wallet with only staked ONE inside
![image](https://user-images.githubusercontent.com/84278683/143027366-deb1602b-645a-4c3e-9882-c978d65d9bd0.png)

**Comment by victaphu** [comment]
Hi @Stakeridoo 
The issue was caused by creating a harmony dao based proposal. I didn't have permissions so I cannot test that application path-way.

If you have the time and can help out
- URL for the test deploy: https://harmony-snapshot.netlify.app/
- Test cases: https://docs.google.com/spreadsheets/d/1wNlHXQ98xNqMtMgvk8iR7HdG1XCKRzN8j_OcMqTIxAU/edit#gid=227830316

We'd have to delete them afterwards tho because this writes directly to the main application db that is in production ...

Best,
Victa
